### ISSUE TITLE
Gestion flexible des SRC des LAS - capacité à gérer les DROMs

### ISSUE THREAD

**Issue by CharlesGaydon** [IGNF/lidar-prod#88]
Seules des données LAS au SRC L93 sont actuellement supportées.

- La [lecture de LAS](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/lidar_prod/tasks/utils.py#L78) se fait avec un écrasement du SRC en Lambert 93. Cet écrasement est initialement du au fait que certaines fichiers LAS d'entrée n'avaient pas de projection définie.
- La BD Uni [est interrogée](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/lidar_prod/tasks/utils.py#L156) en Lambert 93 systématiquement. Si la tabl reçue est vide, un shapefile en L93 [est créé.](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/lidar_prod/tasks/utils.py#L198)

Cf. 
- https://github.com/IGNF/lidar-prod/search?q=lambert
- https://github.com/IGNF/lidar-prod/search?q=epsg

Solution possible : le SRC devrait pouvoir être déterminé d'après le LAS donné en entrée. On peut soit considérer que le LAS aura toujours un SRC, soit donner la possibilité de l'écraser (avec un paramètre dans https://github.com/IGNF/lidar-prod/blob/main/configs/data_format/default.yaml du type `override_epsg=null` par défaut).

**Comment by leavauchier** [comment]
> La BD Uni [est interrogée](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/lidar_prod/tasks/utils.py#L156) en Lambert 93 systématiquement. Si la tabl reçue est vide, un shapefile en L93 [est créé.](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/lidar_prod/tasks/utils.py#L198)

La BD Uni est interrogée en Lambert 93 même dans les DROM ?

**Comment by leavauchier** [comment]
résolu dans https://github.com/IGNF/lidar-prod/pull/102
