### ISSUE TITLE
 Anticiper déprécation d'une commande dans workflow CICD #66 

### ISSUE THREAD

**Issue by CharlesGaydon** [IGNF/lidar-prod#89]
Même que https://github.com/IGNF/myria3d/issues/66

> Cf. cette [ligne du workflow](https://github.com/IGNF/myria3d/blob/a739e007aaa3408662086c3a9e98e8d36928a78b/.github/workflows/cicd.yaml#L91).
> 
> ```
> Run echo "::set-output name=version::$(docker run lidar_prod grep '__version__' package_metadata.yaml| cut -d\" -f2)"
> ```
> 
> > Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by leavauchier** [comment]
Mis à jour dans https://github.com/IGNF/lidar-prod/pull/104
